modules_dir = "artifacts/"

[[module]]
    name = "lefish_sqlite"
    mem_pages_count = 100
    logger_enabled = true

[[module]]
    name = "lefish_game"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/bin/bash/curl"
