[package]
name = "tx_sign"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "tx_sign"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.7.1", features = ["logger"] }
log = "0.4.14"
ed25519-compact = "2"
base64 = "0.20.0"

types = { path = "../types" }

